---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: false
configure_osx: true
configure_sublime: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - Contacts
  - Calender
  - Notes
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Reminders
  - Freeform
  - Music
  - News
  - Keynote
  - Numbers
  - Pages

dockitems_persist:
  - name: "Safari"
    path: "/Applications/Safari.app/"
    pos: 2
  - name: "NetNewsWire"
    path: "/Applications/NetNewsWire.app/"
    pos: 3
  - name: "App Store"
    path: "/Applications/App\ Store.app/"
    pos: 4
  - name: "Telegram"
    path: "/Applications/Telegram.app/"
    pos: 6
  - name: "Signal"
    path: "/Applications/Signal.app/"
    pos: 5
  - name: "WhatsApp"
    path: "/Applications/WhatsApp.app/"
    pos: 8
  - name: "Messages"
    path: "/Applications/Messages.app/"
    pos: 9
  - name: "Spotify"
    path: "/Applications/Spotify.app/"
    pos: 10
  - name: "Bear"
    path: "/Applications/Bear.app/"
    pos: 11
  - name: "Todoist"
    path: "/Applications/Todoist.app/"
    pos: 12
  # - name: "NotePlan"
  #   path: "/Applications/Setapp/NotePlan.app"
  #   pos: 13
  - name: "Fantastical"
    path: "/Applications/Fantastical.app/"
    pos: 14
  - name: "Transmit"
    path: "/Applications/Transmit.app/"
    pos: 15
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 16
  - name: "Sytem Settings"
    path: "/Applications/System Settings.app/"
    pos: 17

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/samlitt/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/personal/dotfiles
dotfiles_home: "~"
dotfiles_files:
  - .zshrc
  - .spaceshiprc.zsh
  - .gitconfig
  - .gitignore
  - .osx

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - spaceship
  - actionlint
  - dockutil
  - borgbackup
  - borgmatic
  - cocoapods
  - croc
  - dart-sdk
  - ffmpeg
  - gettext
  - mas
  - git
  - git-lfs
  - go
  - glow
  - gpg
  - gpgme
  - httpie
  - hugo
  - irssi
  - iperf
  - jq
  - kubernetes-cli
  - sqlite
  - mono
  - mosh
  - node
  - neofetch
  - neovim
  - nvm
  - ssh-copy-id
  - shellcheck
  - tree-sitter
  - cowsay
  - openssl
  - wget
  - youtube-dl
  - r
  - zsh-async
  - zsh-autosuggestions
  - zsh-completions
  - zsh-syntax-highlighting
  - zsh-history-substring-search

homebrew_taps:
  - 1password/tap
  - espanso/espanso
  - homebrew/bundle
  - mongodb/brew
  - teamookla/speedtest

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - iterm2
  - ghostty
  - 1password
  - 1password-cli
  - alt-tab
  - fork
  - duplicati
  - kopiaui
  - espanso
  - obsidian
  - signal
  - docker
  - firefox
  - google-chrome
  - todoist
  - transmit
  - nova
  - netnewswire
  - spotify
  - lunar
  - little-snitch
  - wireshark
  - affinity-photo
  - affinity-designer
  - affinity-publisher
  - iina
  - intellij-idea
  - optimage
  - raycast
  - sdformatter
  - firefly
  - raspberry-pi-imager
  - viscosity
  - visual-studio-code
  - beeper

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1569813296, name: "1Password for Safari" }
  - { id: 948660805, name: "AusweisApp2" }
  - { id: 441258766, name: "Magnet" }
  - { id: 430255202, name: "Mactracker" }
  - { id: 425424353, name: "The Unarchiver" }
  - { id: 411643860, name: "DaisyDisk" }
  - { id: 975937182, name: "Fantastical" }
  - { id: 1091189122, name: "Bear" }
  - { id: 1000808993, name: "Coca" }
  - { id: 1179623856, name: "Pastebot" }
  - { id: 1484348796, name: "Endel" }
  - { id: 1444383602, name: "GoodNotes" }
  - { id: 1544743900, name: "Hush" }
  - { id: 1437226581, name: "Horo" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
